on:
  push:
    branches: [ atulgaurav98-patch-1 ]
env:
  FNAME: "Atul"
  SNAME: "Gaurav"
jobs:
  show:
    name: "example for global env variable"
    runs-on: [self-hosted,Linux,Ubuntu]
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: show env variables
        run: |
          echo "your name is $FNAME $SNAME"
